### PR TITLE
104 Make Batch use product enum

### LINKED ISSUE #104: Make Batch use product enum
The Batch class should use the products enum instead of int. Make sure to fix all places that it is used, including tests.

### PR DESCRIPTION
**Pull request by Teyson**
Closes #104

## Description
Provide details about your Pull Request and what it adds, fixes or
changes.

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes, if necessary.
- [x] All tests pass (existing and potential new).
- [x] Sonar check has passed
- [x] No codesmells or bugs

## Other Relevant Information
Provide any other important details below.

### CODE REVIEW

**Comment by Kechr** [comment]
image
Doesn't build 🤔

**Comment by Teyson** [comment]
> image
> Doesn't build 🤔

It does now babyyyyyyy ;)

**Comment by Kechr** [comment]
> > image
> > Doesn't build thinking
> 
> It does now babyyyyyyy ;)

image
🤔

**Comment by Teyson** [comment]
> > > image
> > > Doesn't build thinking
> > 
> > 
> > It does now babyyyyyyy ;)
> 
> image
> 🤔

I HATE YOU....

**Comment by Teyson** [comment]
> You could write a test where the Products.values returns 0 such that the last test can achieve 100% coverage :)

Great minds think alike, I was doing it while you wrote your comment :)

**Review by Kechr — APPROVED** [review]

**Review by Kaszz — APPROVED** [review]

**Review by Lawst96 — APPROVED** [review]

**Review by dottore1 — APPROVED** [review]

**Pull request merged**
